const SearchActionTypes = {
  SET_SORT_BY_AND_ORDER: "SET_SORT_BY_AND_ORDER",
  SET_SEARCHTEXT: "SET_SEARCHTEXT",
  SET_DEBOUNCED_SEARCHTEXT: "SET_DEBOUNCED_SEARCHTEXT",
}

export default SearchActionTypes
