const MapActionTypes = {
  SET_CURRENT_ROUTES: "SET_CURRENT_ROUTES",
  FETCH_VIDEOS_START: "FETCH_VIDEOS_START",
  FETCH_VIDEOS_SUCCESS: "FETCH_VIDEOS_SUCCESS",
  FETCH_VIDEOS_FAILURE: "FETCH_VIDEOS_FAILURE",
}

export default MapActionTypes
