const VideoActionTypes = {
  SET_VIDEO_IS_PLAYING: "SET_VIDEO_IS_PLAYING",
  SET_VIDEO_LAT_LNGS: "SET_VIDEO_LAT_LNGS",
  SET_VIDEO_CUR_TIME: "SET_VIDEO_CUR_TIME",
  SET_VIDEO_TOTAL_LENGTH: "SET_VIDEO_TOTAL_LENGTH",
  SET_VIDEO_ID: "SET_VIDEO_ID",
}

export default VideoActionTypes
